### ISSUE TITLE
Use more tiles in tomtomWidget for less http requests.

### ISSUE THREAD

**Issue by DeepRootNine** [Echolaitoc/Parissues2016#37]
When the user is translating between two tiles, they have to be constantly requested.

**Comment by Echolaitoc** [comment]
removed all ofLoadUrlAsync from wTomTomMap, instead the ofImages directly load from the url. This is much, much faster, but also revealed a bug where zooming can break the tile positions...
the tiles are still reloaded when translating between two tiles, but since it is lightning fast now, the requests do not bother me
